function gian() {
   document.getElementById("text").innerHTML = random();
}
function random() {
  var arr = [";gabriela tu gosta de dar o cu",
  "sou branco",
  "MLK FDP",
  "TAVA ME TESTANDO",
  "eu odeio minecraft",
  "PUTA MERDA CARALHO CACETE PUTA Q <br>PARIU MERDA</br>",
  "EU NEM SEI OQ É PENSÃO<br>vou sair do assunto <br>voce é mais estranho q eu</br></br>",
  "eu to brabo",
  "COMO TODO MUNDO",
  "eu to de camiseta",
  "eu vou cometer suicidio",
  "se quer ums baguio",
  "eu não sei imitar o som de bulbassauro",
  "pelo menos vou arranjar uma pessoa na minha<br>vida mais rapido</br>",
  "então acho q vou virar gay",
  "o meu pé ta doendo",
  "to com buxin chei",
  "eu não consigo engravidar uma menina",
  "porra tava vendo meu hentai",
  "eu tenho falta de esperma",
  "eu adoro piadas com autismo",
  "eu parei no meio pq meu pai entrou no quarto",
  "eu to chorando",
  "PQ TEM UM CARA COM UMA FOTO DE <br>UMA...</br>",
  "ESQUECI O NOME",
  "MAS E AQUELAS Q TEM NO PLAYBOY",
  "eu so memo",
  "tiktok é um problema",
  "o pedro pegou asma",
  "sabe o passeio?",
  "eu faço isso todo dia",
  "lambendo o yoshi?",
  "biscoito",
  "q foi porra",
  "sopa ou macarrão?",
  "SOU ANTI HOMOSEXUAIS",
  "a bea nem é tão gostosa assim",
  "ja transou com o tio jet?",
  "mano, eu não lembro de ter fodido uma menina",
  "ent se fode",
  "eu tambem tava, so q eu tava fazendo outra<br>coisa</br>",
  "timmothy vc ja tem um filho com o jet",
  "se eu engravidar a bea eu n sei se fico feliz ou triste",
  "EU VO FAZE VIDEO",
  "DE UM SOFA FEIO",
  "Q ISSO",
  "O MOLEQUE TAVA VENDO PORNO DE CLUB PENGUIN",
  "sabia que o satan nao ia apareçer",
  "+deuses quando seu primo rouba tua namorada e ve ela gemendo no quarto dele",
  "monina ta tipo:Ei CeBoLiNha To VeNdo hentai de irmaos",
  "jesus cristo é o meu salvador",
  "abre o server",
  "fodeu muito gente",
  "que gangue bonita.",
  "BIXO JOHN CENA E VC?",
  "ta calor mesmo",
  "fodase vo fazer ship gay memo",
  "dva gorda, nada pra se ver aqui",
  "agora a merda vai ficar boa",
  "+simsimi METE O CU NO RIO",
  "PQ EU PESQUISEI 'MELHORES JOGOS HENTAI' E VEIO AMONG US? Q Q O GOOGLE TA QUERENDO",
  "+simsimi tchau seu buceta",
  "vo invoca um deus",
  "eu nunca postei nsfw no chat geral",
  "pq diabos tem tanto no server?",
  "TIMMOTHY VAMO SAI DAQUI O FASTAO TA PUTO",
  "FIA DA PUTA SO SEU MAIOR FAN",
  "eu to vendo um hentao",
  "+lava hentai de planta",
  "boa noite, e que eu morra",
  "HAMBURGAO",
  "ela nem se importa mais comigo",
  "eu ia perguntar pq o cobre fica azul, mas eu não estudo quimica",
  "a perna e mais grossa que a outra...kkkk",
  "EU TRABALHO NA PORRA DO DONUT WOLF",
  "SEIS NUM JOGAM JOGOS DE VERDADE ISSO AQUI E UM JOGO BAO",
  "PQ SEMPRE Q VAI ATUALIZAR DA A TELA AZUL DA MORTE",
  "e to baxaindo um jogo muto legau",
  "sera que meu pau deveria ta duro pra isso?",
  "MEU PENIS TA DURO",
  "ixi entrou um cara otacu",
  "VAI TOMA NO CU JESUS",
  "MUDA DEMONIO",
  "FALA DEMONIO FALA OQ VC IA FALA",
  "feliz ano novo",
  "pq to com fome",
  "COMO VC N ACHA Q A MAE DROGADA N TEM NADA RELACIONADO",
  "legal supertiago vc fez eu sai da porra do jogo pra ve essa noticia",
  "entrei no server do sata",
  "pq eu morri de cancer do nada?",
  "e meu ovido acabou de se masturbar sangue",
  "gata posso pega?",
  "NAO MECHE COMIGO,EU TENHO PODER DE DEUS E HENTAI NO MEU LADO",
  "tiago...",
  "vc n e feio",
  "vc e o unico bonito pra mim",
  "VAI SE FERRA ELE E LINDO",
  "IXBAGUETE",
  "filha da puta",
  "eu sei hackea um planeta",
  "QUANDO VO VER SEXO NUM JOGO DO MARIO?",
  "odeio crianças",
  "EU ACHEI QUE MARIO ERA PRA CRIANÇA",
  "ALGUEM DEVERIA ESTAR QUEIMANDO NO INFERNO",
  "ta parei",
  "Q PORRA É ESSA",
  "maluco<br>eu ja parei de ser virgem<br>faz tempo</br></br>",
  "fodeo >;D",
  "é pecado isso mano",
  "eu tenho um namorado agora",
  "boomer espermatozoide",
  "odeio crianças",
  "ala o adm",
  "BOITE",
  "boa noitre suets corno",
  "sindromedidal",
  "ACEYEFEFE",
  "como q eu sou homofobico sendo bi?",
  "sonic grávido",
  "gato homossexual",
  "8 da manhã bebendo",
  "eu contei<br>eu tenho 7 cm<br>coitada da bea<br>vou estourar o anus dela<br>ela tem 1,50<br>e eu 1.75",
  "medir o pau mano",
  "ou o jouhn q faz incesto",
  "esperma congelada?",
  "o foda mesmo que eu sou bissexual, e nenhuma mulher me quer, nem as gatinha nem as feia nem as gorda nem as magrinha, mas pra homem, já tem uns 3 homi me querendo e eu sou comprometido"
  ]
  return arr[Math.floor(Math.random() * arr.length)];
}